---
title: "Quotes"
bibliography: bibliography.bib
output: html_document
---

> The so-called "production functions" used by all schools of economic thought that build growth models omit any necessary role for energy, as if output could be produced by labor and capital alone---or as if energy is merely a form of man-made capital that can be produced (as opposed to extracted) by labor and capital.[see @book, pp. 33-35]



> How can I begin anything new with all of yesterday in me?

    Avoid the flourish. Do not be afraid to be weak. Do not be ashamed to be tired. You look good when you’re tired. You look like you could go on forever. Now come into my arms. You are the image of my beauty.

    If you don’t become the ocean, you’ll be seasick every day.

    Reality is one of the possibilities I cannot afford to ignore.



    My reputation as a ladies’ man was a joke that caused me to laugh bitterly through the ten thousand nights I spent alone.

    As our eyes grow accustomed to sight they armor themselves against wonder.

    It’s hard to hold the hand of anyone who is reaching for the sky just to surrender.

    It doesn’t matter what you do because it’s going to happen anyway.



    Music is the emotional life of most people.






